services:
  - type: web
    name: PRAISPRO
    env: docker
    plan: free
    repo: https://github.com/MatiGam92/PRAISPRO
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://your-app.onrender.com
      - key: PORT
        value: "8080"

databases:
  - name: laravel-db
    engine: postgres
    plan: starter
    region: oregon

volumes:
  - name: laravel-storage
    sizeGB: 1
    region: oregon
    mountPath: /var/www/html/storage
